root: true
extends:
  - semistandard
  - plugin:prettier/recommended
rules:
  strict:
    - error
    - safe
  standard/computed-property-even-spacing: false
parserOptions:
  sourceType: script
overrides:
  - files:
      - test/**/*.spec.js
    env:
      mocha: true
